name: CompetitiveWithAnne Update Achieve Release

env:
  TZ: Asia/Shanghai

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Run Tags'
        required: false
  push:
    paths:
      - '**/*.md'
      - '**/*.sp'
    branches:
      - master

jobs:
  release:
    if: github.repository == 'fantasylidong/CompetitiveWithAnne'
    name: Upload CompetitiveWithAnne Achieve if a new commit was been push.
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        run: |
          git clone https://github.com/fantasylidong/CompetitiveWithAnne
          git clone --depth 1 -b zonemod https://github.com/fantasylidong/anne.git

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"

      - name: Gzip
        run: |
          mkdir CompetitiveWithAnne-${{ steps.date.outputs.date }}
          mkdir CompetitiveWithAnne-${{ steps.date.outputs.date }}/left4dead2/
          cp -R CompetitiveWithAnne/* CompetitiveWithAnne-${{ steps.date.outputs.date }}/left4dead2/
          cp -R anne/left4dead2/sound/ CompetitiveWithAnne-${{ steps.date.outputs.date }}/left4dead2/
          cp -R anne/left4dead2/models/ CompetitiveWithAnne-${{ steps.date.outputs.date }}/left4dead2/
          cp -R anne/left4dead2/materials/ CompetitiveWithAnne-${{ steps.date.outputs.date }}/left4dead2/
          cp -R anne/update/ CompetitiveWithAnne-${{ steps.date.outputs.date }}/
          tar -czvf CompetitiveWithAnne-${{ steps.date.outputs.date }}.tar.gz CompetitiveWithAnne-${{ steps.date.outputs.date }}

      - name: Gzip nomysql
        run: |
          rm -f CompetitiveWithAnne-${{ steps.date.outputs.date }}/left4dead2/addons/sourcemod/plugins/chat-processor.smx
          rm -f CompetitiveWithAnne-${{ steps.date.outputs.date }}/left4dead2/addons/sourcemod/plugins/extend/hextags.smx
          rm -f CompetitiveWithAnne-${{ steps.date.outputs.date }}/left4dead2/addons/sourcemod/plugins/extend/rpg.smx
          rm -f CompetitiveWithAnne-${{ steps.date.outputs.date }}/left4dead2/addons/sourcemod/plugins/extend/chatlog.smx
          rm -f CompetitiveWithAnne-${{ steps.date.outputs.date }}/left4dead2/addons/sourcemod/plugins/extend/veterans.smx
          rm -f CompetitiveWithAnne-${{ steps.date.outputs.date }}/left4dead2/addons/sourcemod/plugins/extend/l4d2_damage_show.smx
          rm -f CompetitiveWithAnne-${{ steps.date.outputs.date }}/left4dead2/addons/sourcemod/plugins/extend/punch_angle.smx
          rm -f CompetitiveWithAnne-${{ steps.date.outputs.date }}/left4dead2/addons/sourcemod/plugins/extend/l4d2_blacklist.smx
          rm -f CompetitiveWithAnne-${{ steps.date.outputs.date }}/left4dead2/addons/sourcemod/plugins/extend/l4d2_hitsound.smx
          cp CompetitiveWithAnne-${{ steps.date.outputs.date }}/left4dead2/addons/sourcemod/plugins/disabled/rpg.smx CompetitiveWithAnne-${{ steps.date.outputs.date }}/left4dead2/addons/sourcemod/plugins/extend/
          tar -czvf CompetitiveWithAnne-${{ steps.date.outputs.date }}-nomysql.tar.gz CompetitiveWithAnne-${{ steps.date.outputs.date }}

      - name: Gzip norank&&sourcebans&&lilac
        run: |
          rm -f CompetitiveWithAnne-${{ steps.date.outputs.date }}/left4dead2/addons/sourcemod/plugins/extend/l4d_stats.smx
          rm -f CompetitiveWithAnne-${{ steps.date.outputs.date }}/left4dead2/addons/sourcemod/plugins/extend/sbpp_*
          rm -f CompetitiveWithAnne-${{ steps.date.outputs.date }}/left4dead2/addons/sourcemod/plugins/extend/lilac.smx
          tar -czvf CompetitiveWithAnne-${{ steps.date.outputs.date }}-norank.tar.gz CompetitiveWithAnne-${{ steps.date.outputs.date }}

      - name: Update release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          files: |
            CompetitiveWithAnne-${{ steps.date.outputs.date }}.tar.gz
            CompetitiveWithAnne-${{ steps.date.outputs.date }}-norank.tar.gz
            CompetitiveWithAnne-${{ steps.date.outputs.date }}-nomysql.tar.gz
          tag_name: CompetitiveWithAnne-stable-release-${{ steps.date.outputs.date }}
